name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          git-config-email: misaka10032@aliyun.com
          git-config-name: misaka10032
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: src/.vuepress/dist
          clean: true

  syncToGitee:
    needs: deploy-gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: 同步Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:mi-saka10032/frontend-service-station.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:mi-sa-ka10032/frontend-service-station.git

      - name: 部署Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          #注意替换为你的 Gitee 用户名
          gitee-username: mi-sa-ka10032
          #注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          #注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: frontend-service-station
          #要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages